/**
 * Generates src/components/icons.tsx from the Phosphor icon set (MIT).
 *
 * Importing `phosphor-react-native` directly pulls 1,500 icons and ~10 MB of
 * source through Metro, and deep-importing its .tsx sources drags the package's
 * own type errors into our typecheck. Instead this lifts the `regular` and
 * `fill` path data for only the icons the app actually draws into one small
 * local module.
 *
 * The Phosphor package is a build-time input only, not an app dependency, so
 * install it before regenerating:
 *
 *   npm i --no-save phosphor-react-native
 *   node scripts/build-icons.mjs
 */
import fs from "node:fs";
import path from "node:path";

const ICONS = [
  "Bell",
  "BellRinging",
  "BookmarkSimple",
  "Camera",
  "CaretDown",
  "CaretLeft",
  "CaretRight",
  "Check",
  "CheckCircle",
  "Clock",
  "ClockCounterClockwise",
  "Crosshair",
  "CrosshairSimple",
  "Flame",
  "GridFour",
  "Info",
  "ListDashes",
  "MagnifyingGlass",
  "MapPin",
  "MapTrifold",
  "Minus",
  "NavigationArrow",
  "Plus",
  "Ruler",
  "Sparkle",
  "StackSimple",
  "Storefront",
  "Tag",
  "TrendDown",
  "User",
  "X",
];

const defsDir = path.join(process.cwd(), "node_modules/phosphor-react-native/src/defs");
const out = path.join(process.cwd(), "src/components/icons.tsx");

/** Pull every `d="…"` inside the block for one weight. */
function pathsFor(source, weight) {
  const start = source.indexOf(`'${weight}',`);
  if (start === -1) throw new Error(`weight ${weight} missing`);
  // The block runs to the start of the next `[\n    '` entry, or the end.
  const rest = source.slice(start);
  const end = rest.search(/\n {2}\],/);
  const block = end === -1 ? rest : rest.slice(0, end);
  if (/<(?!Path|\/|>)/.test(block.replace(/<\/?>/g, ""))) {
    throw new Error(`non-Path element in ${weight} block`);
  }
  return [...block.matchAll(/\sd="([^"]+)"/g)].map((m) => m[1]);
}

const entries = ICONS.map((name) => {
  const source = fs.readFileSync(path.join(defsDir, `${name}.tsx`), "utf8");
  return {
    name,
    regular: pathsFor(source, "regular"),
    fill: pathsFor(source, "fill"),
  };
});

const body = entries
  .map(
    (e) =>
      `  ${e.name}: {\n    regular: [\n${e.regular.map((d) => `      ${JSON.stringify(d)},`).join("\n")}\n    ],\n    fill: [\n${e.fill.map((d) => `      ${JSON.stringify(d)},`).join("\n")}\n    ],\n  },`,
  )
  .join("\n");

const file = `/* GENERATED by scripts/build-icons.mjs — do not edit by hand. */
/* Icon paths from Phosphor Icons (https://phosphoricons.com), MIT licensed. */
import React, { memo } from "react";
import Svg, { Path } from "react-native-svg";

import { color as theme } from "@/theme";

export type IconWeight = "regular" | "fill";

export type IconProps = {
  size?: number;
  color?: string;
  weight?: IconWeight;
};

const PATHS: Record<string, Record<IconWeight, string[]>> = {
${body}
};

function makeIcon(name: string) {
  const Icon = ({ size = 16, color = theme.text, weight = "regular" }: IconProps) => (
    <Svg width={size} height={size} viewBox="0 0 256 256" fill={color}>
      {PATHS[name][weight].map((d, i) => (
        <Path key={i} d={d} fill={color} />
      ))}
    </Svg>
  );
  Icon.displayName = name;
  return memo(Icon);
}

${entries.map((e) => `export const ${e.name} = makeIcon("${e.name}");`).join("\n")}
`;

fs.writeFileSync(out, file);
console.log(`wrote ${out} — ${entries.length} icons`);
